name: Build and deploy to S3
on:
  push:
    branches-ignore: "master"

jobs:
  build:
    name: Build and deploy to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6.x"
      - name: build
        env:
          BUNDLER_VERSION: "2.4.1"
        run: |
          gem install bundler
          bundle install
          bundle exec jekyll build
          bundle exec htmlproofer ./_site \
            --allow-hash-href \
            --check-favicon  \
            --check-html \
            --disable-external
      - name: deploy
        run: |
          aws s3 cp \
            --recursive \
            --region us-east-2 \
            _site \
            s3://stripethree.github.io/${GITHUB_REF:11}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
